# Rozpoznawanie gatunku wina

### Przygotowanie danych do uczenia maszynowego

Import dataset'u z biblioteki sklearn oraz podział dataset'u na dwa zbiory: treningowy oraz testowy. Zbiór treningowy zawierać będzie 70% danych, natomiast testowy 30%.

In [29]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

#data = load_wine()

RANDOM_STATE=7
X, y = load_wine(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.30,
                                                    random_state=RANDOM_STATE)
print(y_test)


[2 0 2 2 1 2 1 0 1 2 0 1 2 1 1 1 1 2 0 0 1 1 1 1 0 2 1 2 2 2 1 0 2 1 1 1 2
 2 0 2 0 1 2 2 1 0 0 1 1 1 1 1 0 0]


### Uczenie algorytmem Nearest Centroid

Import biblioteki oraz uczenie na zbiorze treningowym.

In [30]:
from sklearn.neighbors.nearest_centroid import NearestCentroid

clf = NearestCentroid()
clf.fit(X_train, y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

##### Skuteczność na zbiorze treningowym

In [31]:
clf.score(X_train, y_train)

0.7096774193548387

##### Skuteczność na zbiorze testowym

In [32]:
clf.score(X_test,y_test)

0.7592592592592593

##### Przewidywanie wyniku dla pojedynczego elementu zbioru testowego

In [33]:
clf.predict(X_test[4].reshape(1, -1))

array([1])

### Ponowny podział danych na zbiory

Tym razem dzielimy zbiór podstawowy dwukrotnie, najpierw odrzucamy 10% danych (na których można później przeprowadzić testy skuteczności algorytmu) a następnie pozostałe 90% dzielimy na zbiór treningowy i walidacyjny w stosunku 1:4. Uzyskujemy w ten sposób więcej niż jeden zbiór zarówno do testów jak i do uczenia, co może przełożyć się na różne rezultaty w zależności od naszego wyboru.

In [34]:
X, y = load_wine(return_X_y=True)
X2, X_test, y2, y_test = train_test_split(X, y,
                                                    test_size=0.10,
                                                    random_state=RANDOM_STATE)
X_train, X_valid, y_train, y_valid = train_test_split(X2, y2,
                                                    test_size=0.20,
                                                    random_state=RANDOM_STATE)


### Uczenie algorytmem Support Vector Machines

Import biblioteki oraz uczenie na zbiorze treningowym.

In [35]:
from sklearn import svm

clf = svm.SVC(gamma = 'scale')
clf.fit(X2, y2)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

##### Skuteczność na zbiorze treningowym

In [36]:
clf.score(X_train, y_train)

0.828125

##### Skuteczność na zbiorze testowym

In [37]:
clf.score(X_test,y_test)

0.7777777777777778

##### Przewidywanie wyniku dla pojedynczego elementu zbioru testowego

In [38]:
clf.predict(X_test[4].reshape(1, -1))

array([1])

### Uczenie algorytmem Random Forrest

Import biblioteki oraz uczenie na zbiorze treningowym.

In [39]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=13)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=13, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

##### Skuteczność na zbiorze treningowym

In [40]:
clf.score(X_train,y_train)

1.0

##### Skuteczność na zbiorze testowym

In [41]:
clf.score(X_valid,y_valid)

0.96875

##### Przewidywanie wyniku dla pojedynczego elementu zbioru testowego

In [42]:
clf.predict(X_test[4].reshape(1, -1))

array([1])